version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: smartcare-api
    tty: true
    restart: unless-stopped
    image: smartcareapi
    working_dir: /app
    volumes:
      - ./smartcare_backend:/app
    ports:
      - "6969:5000"
    networks:
      - smartcare_network
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_ENV: ${FLASK_ENV}
    env_file:
      - ./.env
    command: ["flask", "run"]

  react:
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: smartcare-react
    tty: true
    restart: unless-stopped
    working_dir: /app
    stdin_open: true
    volumes:
      - ./smartcare_frontend:/app
    environment:
      WDS_SOCKET_PORT: 0
    env_file:
      - ./.env
    networks:
      - smartcare_network
    command: 
      - "/bin/bash"
      - "-c"
      - "npm install && npm start"

  nginx:
    image: nginx:alpine
    container_name: smartcare-nginx
    restart: unless-stopped
    ports:
      - 6970:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    networks:
      - smartcare_network

networks:
  smartcare_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
