version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: smartcare-api
    tty: true
    restart: unless-stopped
    image: smartcareapi
    working_dir: /app
    volumes:
      - ./smartcare_backend:/app
      - ./docker/logs:/logs
      - .env:/.env
    ports:
      - "6969:5000"
    networks:
      - smartcare_network
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_ENV: ${FLASK_ENV}
    env_file:
      - ./.env
    command: ["flask", "run"]

  react:
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: smartcare-react
    tty: true
    restart: unless-stopped
    working_dir: /app
    stdin_open: true
    volumes:
      - ./smartcare_frontend:/app
    environment:
      WDS_SOCKET_PORT: 0
    env_file:
      - ./.env
    networks:
      - smartcare_network

  nginx:
    image: nginx:alpine
    container_name: smartcare-nginx
    restart: unless-stopped
    ports:
      - 6970:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    networks:
      - smartcare_network

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: smartcare-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    env_file:
      - ./.env
    ports:
      - 27020:27017
    volumes:
      - dbdata:/data/db
      - ./docker/mongo:/data/configdb
    networks:
      - smartcare_network


  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: smartcare-mongo-express
    ports:
      - 6971:8081
    environment:
      ME_CONFIG_MONGODB_URL: $MONGO_URI
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_EXPRESS_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_EXPRESS_PASSWORD
    env_file:
      - ./.env
    networks:
      - smartcare_network

networks:
  smartcare_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
